services:
  db:
    image: postgres:alpine3.20
    container_name: postgres_container
    environment:
      POSTGRES_USER: fast-food
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: fast-food
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    platform: linux/x86_64
    build: .
    container_name: fastify-app
    environment:
      DATABASE_URL: postgresql://fast-food:strongpassword@localhost:5432/fast-food
    depends_on:
      - db
    ports:
      - 3000:3000
      - 8080:8080
      - 9240:9240 # Node inspect
    command: ./run.sh

volumes:
  postgres_data:
